org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment Properties
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.124
neo_version_range=[21,)
loader_version_range=[4,)
curseforge_id=1237796
modrinth_id=BOJKcpCJ
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23
## Mod Properties
mod_id=tweakermoreforge
mod_name=TweakerMoreForge
mod_license=GNU LGPL 3.0
mod_version=0.0.8-mc1.21.4
mod_group_id=cn.sh1rocu
mod_authors=Sh1roCu
mod_description=
## Dependence
mafglib_version=0.2.11-mc1.21.4
forgematica_version=0.2.2-mc1.21.4
tweakerge_version=0.2.1-mc1.21.4
rock_roller_version=0.2.2-mc1.21.4
bocchud_version=0.2.2-mc1.21.4
## crashed when runClient in this newest version :)
#embeddium_version=1.21.4:1.0.12-beta.431+mc1.21.4
## no version for 1.21.1+
#nolijium_version=0.5.6
